version: "3"

services:
  app:
    container_name: api
    restart: always
    build: .
    ports:
      - "5555:5555"
    links:
      - mongodb
    volumes:
      - .:/app
  mongodb:
    container_name: database
    image: mongo
